# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='不願意透漏身份的人', max_length=10),
        ),
    ]
